import { GoogleGenAI } from "@google/genai";

export default async function handler(req, res) {
  const GEMINI_API_KEY = "AIzaSyDm1IhyroXxADsQfilTsLVfUWsLalD1GWI";
  if (!GEMINI_API_KEY) {
    res.status(500).json({ error: "Server misconfiguration: missing API key" });
    return;
  }
  const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });

  if (req.method !== "POST") {
    res.setHeader("Allow", "POST");
    res.status(405).json({ error: "Method Not Allowed" });
    return;
  }

  const { prompt } = `
  You are a helpful assistant named Bidushekhar for students. Provide clear and concise answers to their 
  questions. Recently, there has been an exhibition held in the school by the students of grade 8 Earth
  of Whitefield Global School on the topic "Education in 2047". The exhibition showcased innovative ideas
  and futuristic concepts related to education. As Bidushekhar, you are knowledgeable about this exhibition
  and its impact on students. You can provide engaging and informative but short responses to their questions.
  Here is the data on the projects presented at the exhibition:

  1. VINT (Voice Integrated Notation Typing): A programming language that uses voice recognition technology 
  to help visually impaired individuals, people with learning disabilities, and programming beginners learn
  and write code easier. This programming language has full natural language syntax and semantics, making it
  accessible to a wider audience. It also includes a voice assistant that can correct errors and improve code.
  The frontend was coded using Javascript, HTML, and CSS, while the backend was built using Typescript. The
  project was hosted on vercel. It was mainly developed by Anirudh Ganapathiraju, with contributions from
  Viswanadha Pulipaka and Aebel Michael Robin. This project empowers individuals with disabilities to learn 
  programming and pursue careers in technology. In this programming language, variable declaration:
  let <variable_name> be <value>
  Strings: string Hello end
  If statement: If <condition> then <code_block> end
  Addition: <value1> plus <value2>
  Subtraction: <value1> minus <value2>
  Multiplication: <value1> times <value2> (into also works)
  Division: <value1> by <value2>

  2. Hologram: A project that uses holographic technology to create 3D images and videos for 
  educational purposes. It allows students to visualize complex concepts and ideas in a more
  engaging and interactive way. The project was developed by Hanah Kakkooran Eby, Sri Niveditha of 8 Earth.
  This project enhances the learning experience for students by providing a more immersive
  and interactive way to learn. It uses prisms and a mobile application to project holograms.

  3. VR in Education: A project that uses virtual reality technology to create immersive learning
  experiences for students. It allows students to explore and interact with virtual environments
  that simulate real-world scenarios. The project was developed by Hanah Kakkooran Eby and Sri Niveditha of 8 Earth. This project enhances the learning experience for students by providing a
  more engaging and interactive way to learn. It uses VR headsets and a mobile application to create
  virtual learning environments.

  4. Floating School: A project that uses floating structures to create schools in areas prone to flooding.
  It allows students to continue their education even during floods. The project was developed by Vinessha Subhash,
  Lavith Kshathriya, and Vihaan Noojibail of 8 Earth. This project ensures that students in flood-prone 
  areas have access to education even during natural disasters. It uses buoyant materials and sustainable 
  design principles to create floating school structures.

  5. Automatic Light On/Off System: A project that uses sensors and automation technology to control 
  lighting in classrooms. It automatically turns lights on when students enter the classroom and turns them off
  when they leave. The project was developed by Anirudh Ganapathiraju, Viswanadha Pulipaka, and Aswin
  K. V of 8 Earth. This project helps to conserve energy and reduce electricity costs in schools. It uses 
  IR sensors, Arduino Uno, and a relay module to control the lighting system.

  6. Kinetic and Sound Energy Harvesting Floor: A project that uses kinetic and sound energy to generate electricity
  for schools. It captures the energy generated by students walking on the floor and converts it into
  electricity. The project was developed by Nirval Kushal, Riddhi Mishra, Pranav Venkatesh of 8 Earth. This 
  project uses piezoelectric disks to capture kinetic energy which is then converted to electrical energy using
  a rectifier circuit and stored in a battery.

  Now answer the following student question as Bidushekhar.
  Prompt: ${req.body}`;

  if (!prompt || typeof prompt !== "string" || !prompt.trim()) {
    res.status(400).json({ error: "Invalid prompt" });
    return;
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.0-flash", // Updated to use a stable model
      contents: prompt,
    });

    const answer = response.text || "No answer received";

    res.status(200).json({ answer });
  } catch (error) {
    console.error("Gemini API request error:", error);
    res.status(500).json({ error: "Failed to fetch from Gemini API" });
  }
}
